### ISSUE TITLE
How to customize images adding required packages

### ISSUE THREAD

**Issue by informatica92** [bitnami/bitnami-docker-airflow#48]
I recently managed to edit the default `docker-compose.yml` file in order to use customized versions of the images that bitnami provides.
Since I had to do some modifications, I think that it would be a good idea to share the requred steps with you.
First of all you need to add these additional packages when the already existing ones are not enough or in general when you want to execute custom actions after the container creation.

First I added 3 subfolders as you can see below and I added a `Dockerfile `inside each of them
```
.
├── README.md
├── airflow
│   └── Dockerfile
├── airflow-scheduler
│   └── Dockerfile
├── airflow-worker
│   └── Dockerfile
├── docker-compose.yml
...
```

Each Docker file has more or less the same content inside.
```
FROM  bitnami/airflow:1
USER root
RUN apt-get update
RUN apt-get install libgomp1 -y
```
The only thing that is different in my case is the FROM part where I added different image name according to the directory name

Finally, the the `docker-compose.yml` becomes:
```
airflow:
    #image: bitnami/airflow:1
    build: './airflow'
    ...
```
for each service. In other words: replace image tag with build tag and this tag now looks for a file in a different subfolder.

Hope this helps.

**Comment by marcosbc** [comment]
Thanks for sharing! Like you mentioned, extending the Docker image will allow you to modify the existing image to do things such as modifying files or adding new ones, for instance.

In this specific case we would recommend you use `install_packages` instead of `apt-get`:

```
RUN install_packages libgomp1
```

That function takes care of cleaning up afterwards, to reduce the resulting container image size.

Since it does not seem to be an actual issue using the image, I'm closing this but feel free to update with any additional comments after closed.

**Comment by informatica92** [comment]
Do you also suggest to keep the `RUN apt-get update` anyway? 
And yes, it is not an issue but it could be useful to many people that are using this image

**Comment by marcosbc** [comment]
The `install_packages` already takes care of executing `apt-get update` so it's not needed.
