### ISSUE TITLE
1001 user has no entry in /etc/passwd

### ISSUE THREAD

**Issue by aditiagarwal30nov** [bitnami/bitnami-docker-airflow#53]
Getting 
"I have No name!" error for user 1001
No entry in /etc/passwd.

![image](https://user-images.githubusercontent.com/2275445/88356309-f312b000-cd99-11ea-9f60-658b5d10586c.png)

**Comment by juan131** [comment]
Hi @aditiagarwal30nov 

That's something expected. This container is compatible with arbitrary UIDs, which means you can run the container using any UID you want, e.g.:

```
$ docker run --user 1234 bitnami/airflow
```

This is very important to be compatible with some K8s platforms such as Openshift, since these platforms use random UIDs to deploy the containers by default.

Since we cannot assume the UID of the user that will be running the container, we cannot add it to `/etc/passwd` but it doesn't affect Airflow.
